## TODO: Not quite working yet...

# name: StoryApp
# options:
#   bundleIdPrefix: com.mthole
# settings:
#   DEVELOPMENT_TEAM: TV6KLL8Y79
# packages:
#   OpenAI:
#     url: https://github.com/MacPaw/OpenAI.git
#     from: "0.3"
#   StoryData:
#     path: StoryData
# targets:
#   StoryApp:
#     type: application
#     platform: iOS
#     deploymentTarget: "18.0"
#     sources: [StoryApp]
#     settings:
#       base:
#         CODE_SIGN_ENTITLEMENTS: StoryApp/StoryApp.entitlements
#         INFOPLIST_FILE: StoryApp/Info.plist
#     dependencies:
#       - package: OpenAI
#       - package: StoryData
